"""initial production schema

Revision ID: d570b43fba10
Revises: 
Create Date: 2026-09-24 10:21:56.521912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd570b43fba10'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tone', sa.String(length=200), nullable=False),
    sa.Column('public_key', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('hours', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=False),
    sa.Column('whatsapp', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=40), nullable=False),
    sa.Column('daily_token_budget', sa.Integer(), nullable=False),
    sa.Column('chatwoot_url', sa.String(length=300), nullable=False),
    sa.Column('chatwoot_token', sa.String(length=200), nullable=False),
    sa.Column('chatwoot_inbox_id', sa.Integer(), nullable=False),
    sa.Column('external_search_enabled', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_businesses_public_key'), ['public_key'], unique=True)

    op.create_table('event_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('event', sa.String(length=40), nullable=False),
    sa.Column('intent', sa.String(length=30), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('tools', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('issues', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_est', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_logs_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_logs_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_logs_created'), ['created'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_logs_event'), ['event'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_logs_request_id'), ['request_id'], unique=False)

    op.create_table('external_searches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('query', sa.String(length=500), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('answer_used', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('external_searches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_searches_business_id'), ['business_id'], unique=False)

    op.create_table('rate_limit_buckets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bucket_key', sa.String(length=120), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bucket_key', 'window_start', name='uq_rate_window')
    )
    with op.batch_alter_table('rate_limit_buckets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rate_limit_buckets_bucket_key'), ['bucket_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_rate_limit_buckets_window_start'), ['window_start'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('advisor_name', sa.String(length=100), nullable=False),
    sa.Column('facts', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_phone'), ['phone'], unique=False)

    op.create_table('knowledge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_category'), ['category'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_name'), ['name'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('handoff_at', sa.DateTime(), nullable=True),
    sa.Column('handoff_reason', sa.String(length=200), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_state'), ['state'], unique=False)

    op.create_table('appointments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('contact', sa.String(length=200), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('need', sa.Text(), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_start'), ['start'], unique=False)

    op.create_table('leads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=False),
    sa.Column('need', sa.Text(), nullable=False),
    sa.Column('problem', sa.Text(), nullable=False),
    sa.Column('service_interest', sa.String(length=200), nullable=False),
    sa.Column('budget', sa.String(length=100), nullable=False),
    sa.Column('urgency', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('temperature', sa.String(length=20), nullable=False),
    sa.Column('next_action', sa.String(length=300), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=False),
    sa.Column('last_interaction', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leads_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_leads_temperature'), ['temperature'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=False),
    sa.Column('tokens_out', sa.Integer(), nullable=False),
    sa.Column('cost_est', sa.Float(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))

    op.drop_table('messages')
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leads_temperature'))
        batch_op.drop_index(batch_op.f('ix_leads_status'))
        batch_op.drop_index(batch_op.f('ix_leads_source'))
        batch_op.drop_index(batch_op.f('ix_leads_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_leads_business_id'))

    op.drop_table('leads')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_start'))
        batch_op.drop_index(batch_op.f('ix_appointments_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_business_id'))

    op.drop_table('appointments')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_state'))
        batch_op.drop_index(batch_op.f('ix_conversations_business_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_name'))
        batch_op.drop_index(batch_op.f('ix_products_category'))
        batch_op.drop_index(batch_op.f('ix_products_business_id'))

    op.drop_table('products')
    with op.batch_alter_table('knowledge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_category'))
        batch_op.drop_index(batch_op.f('ix_knowledge_business_id'))

    op.drop_table('knowledge')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_phone'))
        batch_op.drop_index(batch_op.f('ix_customers_business_id'))

    op.drop_table('customers')
    with op.batch_alter_table('rate_limit_buckets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rate_limit_buckets_window_start'))
        batch_op.drop_index(batch_op.f('ix_rate_limit_buckets_bucket_key'))

    op.drop_table('rate_limit_buckets')
    with op.batch_alter_table('external_searches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_searches_business_id'))

    op.drop_table('external_searches')
    with op.batch_alter_table('event_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_logs_request_id'))
        batch_op.drop_index(batch_op.f('ix_event_logs_event'))
        batch_op.drop_index(batch_op.f('ix_event_logs_created'))
        batch_op.drop_index(batch_op.f('ix_event_logs_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_event_logs_business_id'))

    op.drop_table('event_logs')
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_businesses_public_key'))

    op.drop_table('businesses')
    # ### end Alembic commands ###
